name: Run Main Script

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run main script
      run: python main.py
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: rachford-rice-results
        path: |
          summary.txt
          case-summary.txt
          case-summary-detailed.txt